---
title: The Debt Collective
timezone: UTC
collections:
  news_analysis:
    title: News Analysis
    output: true
    permalink: "/news-analysis/:name"
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
    permalink: "/profiles/:title"
  uploads:
    title: Uploads
    output: true
author: The Debt Collective
email: organizers@debtcollective.org
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
rss: rss
theme: jekyll-debtcollective
plugins: 
