---
title: The Debt Collective
timezone: UTC
collections:
  artwork:
    title: Artwork
    output: true
    permalink: "/artwork/:name"
  news_analysis:
    title: News Analysis
    output: true
    permalink: "/news-analysis/:name"
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
    permalink: "/profiles/:title"
  uploads:
    title: Uploads
    output: true
    permalink: "/:name"
defaults:
- scope:
    path: news_analysis
    type: posts
  values:
    layout: news-anlysis
    strike-title: striked out title
    lifted-from: where the article came from
author: The Debt Collective
email: organizers@debtcollective.org
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
rss: rss
plugins: 
markdown: kramdown