---
title: The Debt Collective
timezone: UTC
collections:
  artwork:
    title: Artwork
    output: true
    permalink: "/artwork/:name"
    src: the url of the image
    description: A description to help screen readers
    artist: the artist who made the artwork
  news_analysis:
    title: News Analysis
    output: true
    permalink: "/news-analysis/:name"
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
    permalink: "/profiles/:title"
  uploads:
    title: Uploads
    output: true
    permalink: "/:name"
defaults:
- scope:
    path: ""
    type: news_analysis
  values:
    layout: news-anlysis
    strike-title: striked out title
    lifted-from: where the article came from
- scope:
    path: ""
    type: posts
  values:
    author: the author of the piece, if any, or the place the article was originally taken from, if a news-analysis
    sub-title: (optional) a sub title to accompany the piece
    youtube-id: (optional) the last part of a youtube url if a video should accompany the piece
    image: (optional) an image if the piece has a featured image to display
    summary: (optional) a summary of the piece
- scope:
    path: ""
    type: artwork
  values:
    preview: a smaller version of the image to serve as fast loading preview
    src: the full version of the image
    artist: the artist's name
    featured: false
    description: A brief description to accompany the artwork and assist screen-readers
- scope:
    path: ""
    type: profiles
  values:
    layout: profile
    author: the name of the interviewer
    sub-title: a subtitle or excerpted quote from the interview
    youtube-id: (optional) the last part of a youtube url if the interview is a video interview
    video-description: (optional) if there's a video, this will appear over the video while it is paused underneath the title
author: The Debt Collective
email: organizers@debtcollective.org
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
rss: rss
plugins: 
markdown: kramdown
