---
title: The Debt Collective
timezone: UTC
collections:
  artwork:
    title: Artwork
    output: true
    permalink: "/artwork/:name/index.html"
  letters:
    title: Letters
    output: true
    permalink: "/letters/:title/index.html"
  news_analysis:
    title: News Analysis
    output: true
    permalink: "/news-analysis/:title/index.html"
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
    permalink: "/profiles/:title/index.html"
  special_reports:
    title: Special Reports
    output: true
    permalink: "/reports/:title/index.html"
  uploads:
    title: Uploads
    output: true
    permalink: "/:name"
defaults:
- scope:
    path: ''
    type: news_analysis
  values:
    layout: news-anlysis
    strike-title: ''
    lifted-from: ''
- scope:
    path: ''
    type: special_reports
  values:
    layout: special-report
    sub-title: 
    author: 
    youtube-id: 
    image: 
    summary: 
- scope:
    path: ''
    type: news_analysis
  values:
    layout: news-analysis
    sub-title: 
    author: 
    youtube-id: 
    image: 
    summary: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: 
    sub-title: 
    youtube-id: 
    image: 
    summary: 
- scope:
    path: ''
    type: artwork
  values:
    layout: artwork
    preview: link to a smaller version of the image to serve as fast loading preview
    src: link to the full version of the image
    artist: the artist's name
    featured: false
    description: A brief description to accompany the artwork and assist screen-readers
- scope:
    path: ''
    type: letters
  values:
    layout: letter
    author: 
    sub-title: 
    interviewee-picture: 
- scope:
    path: ''
    type: profiles
  values:
    layout: profile
    author: 
    sub-title: 
    interviewee-picture: 
    youtube-id: 
    video-description: 
permalink: pretty
author: The Debt Collective
email: organizers@debtcollective.org
description: The Debt Collective Power Report — Member Profiles, News Analysis, Updates
  on our work
rss: rss
discourse:
  endpoint: https://community.debtsyndicate.org
  paths:
    campaigns: "/campaigns"
    collectives: "/collectives"
    events: "/calendar"
plugins:
- jekyll-seo-tag
markdown: kramdown
exclude:
- ".circleci"
