---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.15
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    working_directory: ~/powerreport.debtcollective.org
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: build site
          command: |
            bundle install
            bundle exec jekyll build
      - run:
          name: deploy to S3
          command: aws s3 sync _site s3://powerreport.debtcollective.org --region us-east-1 --acl public-read
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
